# Generated by Django 3.1.7 on 2021-03-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RooOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='RooPersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('roopersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.roopersonmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.roopersonmodel',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('rooordermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.rooordermodel')),
                ('status', models.CharField(choices=[('n', 'new'), ('d', 'design'), ('r', 'po-raised'), ('a', 'po-accepted'), ('c', 'po-complete'), ('o', 'out-for-delivery'), ('s', 'delivery-complete'), ('x', 'complete')], default='n', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.customer')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.rooordermodel',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('roopersonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.roopersonmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.roopersonmodel',),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('rooordermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.rooordermodel')),
                ('status', models.CharField(choices=[('c', 'created'), ('a', 'accepted'), ('s', 'completed')], default='c', max_length=15)),
                ('base_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.order', verbose_name='Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.supplier')),
            ],
            options={
                'abstract': False,
            },
            bases=('sales.rooordermodel',),
        ),
    ]
